[project]
name = "gameoflife"
version = "0.1.0"
description = "Game of Life by John Conway"
authors = [
    {name = "Arbroen",email = "info@arbonit.nl"}
]
readme = "README.md"
# numpy dictates >3.9
requires-python = ">=3.10"
dependencies = [
    "click (>=8.1.8,<9.0.0)",
    "python-decouple (>=3.8,<4.0)",
    "numpy (>=2.2.1,<3.0.0)",
    "colorama (>=0.4.6,<0.5.0)",
]

[project.optional-dependencies]
# Essentially pip's "extras" argument used by tox. Thus these are not version-pinned!
linters = ["black", "flake8", "isort"]
tests = ["pytest", "pytest-cov", "coverage"]
security = ["safety", "bandit"]

[tool.poetry]
packages = [
    { include = "gol", from = "src" },
]

[tool.poetry.scripts]
gol = "gol.start:game_of_life_command"

[tool.poetry.group.dev.dependencies]
# Pycharm requires setuptools -> isolate as dev dependency.
setuptools = "^78.1.1"
black = "^24.10.0"
flake8 = "^7.1.1"
pytest = "^8.3.4"
tox = "^4.23.2"
safety = "^3.2.14"
bandit = "^1.8.0"
pytest-cov = "^6.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"