[coverage:run]
branch = True
source =
    gol
omit =
    */__version__.py
    */start.py

[coverage:paths]
source =
   src/gol
   .tox/*/lib/python*/site-packages/gol
   .tox/pypy*/site-packages/gol

# Black advises a line-length of 88.
[flake8]
max-complexity = 10
max-line-length = 88

[isort]
include_trailing_comma = true
multi_line_output = 3

[tox]
isolated_build = true
envlist = py, report, linters

# All linter environments below.
[testenv]
setenv =
    LANG=en_US.utf-8
    LC_ALL=en_US.utf-8
extras =
    tests
commands =
    pytest --cov --cov-append

[testenv:report]
depends =
    py
extras =
    tests
commands =
    coverage report
    coverage html

[testenv:safety]
description =
    Check whether there are security issues with dependencies.
commands =
    safety check

[testenv:bandit]
description =
    Check whether there are obvious security issues with codebase.
deps =
    bandit
commands =
    bandit -r src/gol/

[testenv:flake8]
description =
    Validate PEP8 compliance.
deps=
    flake8
    pep8-naming
    flake8-print
    flake8-colors
commands =
    flake8

[testenv:mypy]
description =
    Validate mypy static typing.
deps =
    mypy
commands =
    mypy src --ignore-missing-imports

[testenv:black]
description =
    Validate whether black auto-formatting has been applied.
deps =
    black
commands =
    black src/ tests/ --check

[testenv:isort]
description =
    Sort python imports alphabetically in logical sections.
deps =
    isort
commands =
    isort src tests

[testenv:linters]
description =
    Apply various tools, see tox -a -v
extras =
    security
    linters
commands =
    {[testenv:black]commands}
    {[testenv:isort]commands}
    {[testenv:flake8]commands}
    {[testenv:bandit]commands}
