__author__ = "Jeroen Arbon"
__version__ = "0.0.1"
__package_name__ = "gol"
__project__ = "Game of Life"
__email__ = "jeroen.arbon@gmail.com"
__description__ = "Shining implementation of the Game of Life."
